// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzHq9XhDlpxiIJ7AoH0rkt1dm1UMdXwZ8',
    appId: '1:714025929028:web:6961b6b67c9bdf2030af11',
    messagingSenderId: '714025929028',
    projectId: 'smit-devathon',
    authDomain: 'smit-devathon.firebaseapp.com',
    storageBucket: 'smit-devathon.appspot.com',
    measurementId: 'G-Z4T1NG4BEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8NEdQrUHu62MCRjwpUrd3EVW1fILqJc',
    appId: '1:714025929028:android:e095c1256f1f9c8c30af11',
    messagingSenderId: '714025929028',
    projectId: 'smit-devathon',
    storageBucket: 'smit-devathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKg6y3m1WNp7_P9gkgCloKWaOTlLUWNbc',
    appId: '1:714025929028:ios:340b30cc66aaabf430af11',
    messagingSenderId: '714025929028',
    projectId: 'smit-devathon',
    storageBucket: 'smit-devathon.appspot.com',
    iosBundleId: 'com.example.smithackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKg6y3m1WNp7_P9gkgCloKWaOTlLUWNbc',
    appId: '1:714025929028:ios:0b14384d1b34372030af11',
    messagingSenderId: '714025929028',
    projectId: 'smit-devathon',
    storageBucket: 'smit-devathon.appspot.com',
    iosBundleId: 'com.example.smithackathon.RunnerTests',
  );
}
